### ISSUE TITLE
Link to Home Assistant integration

### ISSUE THREAD

**Issue by myTselection** [KillianMeersman/telemeter#10]
Hi Killian, just want to let you know that I've build a custom Home Assistant integration to integrate Telenet usage details: https://github.com/myTselection/telenet_telemeter. 
The main Telenet connection has been based on your telemeter code. Thanks for that! I have further extended it to also get mobile usage details.

If you want, it might be interesting to also add a link towards this HA integration in your repo, as it may be relevant for users looking into your github repo...

**Comment by KillianMeersman** [comment]
Hi,

I've wanted to create a hass integration for a while now but always lacked the time, so thanks :).
If you'd like, you can contribute your additions for mobile usage data back into this repo via a PR.

I'll add a link to your integration in the README.
